export declare const AVAILABLE_QUERY_OPERATORS: Set<string>;
export declare const SCHEMAS: Set<string>;
export declare const DATAPOINTS = "datapoints";
export declare const ENTITIES = "entities";
export declare const CONCEPTS = "concepts";
export declare const AVAILABLE_FROM_CLAUSE_VALUES: Set<string>;
export declare function validateQueryStructure(query: any, options?: {}): Promise<string | void>;
export declare function validateQueryDefinitions(query: any, options?: {}): void;
export declare function isSchemaQuery(query: any): boolean;
export declare function isDatapointsQuery(query: any): boolean;
export declare function isEntitiesQuery(query: any): boolean;
export declare function isConceptsQuery(query: any): boolean;
